### PR TITLE
Fix typo in install docs

### PR DESCRIPTION
**Pull request by benleb**
# Description

self-explaining

## Related issues
-

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

# Checklist

- [x] The pull request is for the branch develop
- [ ] A new analyzer or connector was added, in which case:
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](./Advanced-Usage.md) was updated (incase the analyzer/connector provides additional optional configuration).
    - [ ] Secrets were added in [env_file_app_template](https://github.com/intelowlproject/IntelOwl/blob/master/docker/env_file_app_template), [env_file_app_ci](https://github.com/certego/IntelOwl/blob/master/docker/env_file_app_ci) and in the [Installation](./Installation.md) docs, if necessary.
    - [ ] If the analyzer/connector requires mocked testing, `_monkeypatch()` was used in it's class to apply the necessary decorators.
    - [ ] If a File analyzer was added, it's name was explicitly defined in [test_file_scripts.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_file_scripts.py) (not required for Observable Analyzers).
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [ReadMe - Legal Notice](https://github.com/certego/IntelOwl/blob/master/README.md) section.
- [ ] The tests gave 0 errors.
- [ ] `Black` gave 0 errors.
- [ ] `Flake` gave 0 errors.
- [ ] The commits were squashed into a single one (optional, they will be squashed anyway by the maintainer)
  
### Important Rules
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review

### CODE REVIEW

**Comment by mlodic** [comment]
thank you but we won't pollute the history with a commit for a typo. I need to reject the PR.

**Comment by benleb** [comment]
no problem, but just for my curiosity... how do you fix typos like this then? doing a PR for something completely unrelated and smuggling in a commit to fix a typo?! 😂 or do you simply not care about your docs?

**Comment by mlodic** [comment]
not so friendly mate but point taken. I wanted to reopen the PR to merge it but you just closed it. If you reopen it, I'll merge it.

**Comment by benleb** [comment]
sorry 😊 🤝

**Pull request merged**
