### PR TITLE
analyzer support for ipv6

### LINKED ISSUE #1885: Support for ipv6 addresses
We should add the chance to analyze ipv6 addresses like any other ipv4 address. We should fix it both in the frontend and the backend regex.

Plus, we should check out the integrated services to understand whether they need some internal change or not to support it (maybe some different functions in the libraries)

### PR DESCRIPTION
**Pull request by shivam-Purohit**
IPv6 closes #1885

# Description
Add ipv6 support for the analyzers 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector, visualizer, playbook or ingestor) was added or changed, in which case:
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](./Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook in `playbook_config.json`.
    - [ ] Check if it could make sense to add that analyzer/connector to other freely available playbooks.
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](./Contribute.md)).
- [] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by shivam-Purohit** [comment]
I am getting positive response for ipapi but most analyzers do not support ipv6. I am confused if I have to add some more support in the backend as of now no tests are failing.

one more thing
when I was installing the app I had to make some changes in the Dockerfile.  I had to change 
```
RUN npm install npm@latest --location=global \
    && npm install \
    && PUBLIC_URL=/static/reactapp/ npm run build
```

i removed the `npm install npm@latest --location=global`  as it was installing some version that was not compatible.
This was the error i was getting

```
1.879 npm ERR! engine Not compatible with your version of node/npm: npm@10.2.1

1.879 npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.1

1.879 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}

1.879 npm ERR! notsup Actual:   {"npm":"8.11.0","node":"v16.15.1"}


```

i am running node 18.18.2 and npm 10.2.0. I don't know why its not showing the actual versions. I cannot build the app, I have to remove the npm update line.

**Comment by mlodic** [comment]
yep the changes requested are more complicated than what you have done, you surely need to touch the backend and fix the regex there too.

Plus we would need to test the majority of analyzer which support IP addresses now (at least the ones in the "FREE_TO_USE_ANALYZERS" playbook) and see if they need some changes. Otherwise, this feature could be a double-edged sword if every analyzer fails. That would be a very bad user experience

**Comment by shivam-Purohit** [comment]
> yep the changes requested are more complicated than what you have done, you surely need to touch the backend and fix the regex there too.

I have gone through the backend  We are defining the observable type in api_app/analyzer_manager/constants.py.

```
    def calculate(cls, value: str) -> str:
        """Returns observable classification for the given value.\n
        Only following types are supported:
        ip, domain, url, hash (md5, sha1, sha256), generic (if no match)

        Args:
            value (str):
                observable value
        Returns:
            str: one of `ip`, `url`, `domain`, `hash` or 'generic'.
        """
        try:
            ipaddress.ip_address(value)
        except ValueError:
            if re.match(
                r"^.+://[a-z\d-]{1,200}"
                r"(?:\.[a-zA-Z\d\u2044\u2215!#$&(-;=?-\[\]_~]{1,200})+"
                r"(?::\d{2,6})?"
                r"(?:/[a-zA-Z\d\u2044\u2215!#$&(-;=?-\[\]_~]{1,200})*"
                r"(?:\.\w+)?",
                value,
            ):
                classification = cls.URL
            elif re.match(
                r"^([\[\\]?\.[\]\\]?)?[a-z\d-]{1,63}"
                r"(([\[\\]?\.[\]\\]?)[a-z\d-]{1,63})+$",
                value,
                re.IGNORECASE,
            ):
                classification = cls.DOMAIN
            elif (
                re.match(r"^[a-f\d]{32}$", value, re.IGNORECASE)
                or re.match(r"^[a-f\d]{40}$", value, re.IGNORECASE)
                or re.match(r"^[a-f\d]{64}$", value, re.IGNORECASE)
            ):
                classification = cls.HASH
            else:
                classification = cls.GENERIC
                logger.info(
                    "Couldn't detect observable classification"
                    f" for {value}, setting as 'generic'"
                )
        else:
            # it's a simple IP
            classification = cls.IP

        return classification

```
we are using ipaddress library to check if its a valid IP address. As I can see [here](https://docs.python.org/3/library/ipaddress.html) it supports both ipv4 and ipv6 addresses. So there shouldn't be an issue checking for v6 as well. As we in this function checking its against ipaddress library and throwing error if it fails to  recognise.  I dont see any other files were we are checking it against regular expression.


Also I ran a test IP against the playbook free analyzers. All of them are showing status 200 with some showing response while others returning no results mostly as they dont support ipv6.
I dont think we would need to check for each analyzer as it would have at least thrown error as unsupported IP addresses. If its not then I think I would have to move to each analyzer documentation to check for ipv6 info.
ubuntuMachine  Running  - Oracle VM VirtualBox 21-10-2023 19_15_51

**Comment by mlodic** [comment]
thank you for that analysis, really appreciated.

**Pull request merged**
