### PR TITLE
[release] v2.5.0

### PR DESCRIPTION
**Pull request by Eshaan7**
# Checklist for creating a new release

- [x] Update `CHANGELOG.md` for the new version
- [x] Change version number in `conf.py`, `.env` and  `schema.yml`
- [x] Verify CI Tests
- [x] Create release for the branch `develop`
- [x] Wait for dockerHub to finish the builds
- [x] Merge the PR to the `master` branch with the "Create a merge commit" strategy.
- [x] Since the next release from this is gonna be the v3, we should also add a note in CHANGELOG.md saying something like "Last stable release in v2. Next release is gonna bring many new features and breaking changes."

**Note:** Only use "Merge and commit" as the merge strategy and not "Squash and merge". Using "Squash and merge" makes history between branches misaligned.

### CODE REVIEW

**Comment by mlodic** [comment]
One thing: could we wait maximum 2 days until I get an answer from the DockerHub team?

In this way we can enable rendertron and have evertyhing back in control again.

**Comment by Eshaan7** [comment]
Yeah, we can wait. There's no particular hurry.

**Comment by mlodic** [comment]
Ok so I'll update this soon

**Comment by mlodic** [comment]
Ok I have configured the intelowl_rendertron repo correctly in Dockerhub. We can make the release

We can ignore this [commit](https://github.com/intelowlproject/IntelOwl/commit/2ce5e668ad0ab23eae1b02f1fa1452ae7a2098f5) I made directly in `master` to mitigate the problem while performing the merge.

**Pull request merged**
