### PR TITLE
Yara forge analyzer

### PR DESCRIPTION
**Pull request by decodingafterlife**
YARA Forge Analyzer #2035 

# Description

Added yara forge analyzer

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/IntelOwl/contribute/) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by mlodic** [comment]
hey, thanks for the interesting in the project. Please do not remove part of the PR checklist, we use it to understand the status of the PR.

About the PR, please follow through the documentation about how to create a new analyzer. For this task, you don't need to create a docker integration, that is over-engineering the problem. A classic analyzer would make its work.

**Comment by decodingafterlife** [comment]
Sorry my bad, I'll try doing it through a normal analyzer. I have university exams going on so I'll need some time (10 days) before I can get back to this.

**Comment by mlodic** [comment]
np @decodingafterlife! We are happy to have you here!

**Comment by mlodic** [comment]
I'll close this due to the imminent new release and due to the fact that the approach was incorrect. 

This task must be addresses together with the Yara-X issue. See https://github.com/intelowlproject/IntelOwl/issues/2035 for updates

**Pull request closed without merging**
