### PR TITLE
ja4db analyzer, closes #2361 

### LINKED ISSUE #2361: [Analyzer] JA4_DB
## Name
JA4_DB

## Link
https://ja4db.com

## Type of analyzer
generic -> ja4 fingerprints only must be accepted

## Why should we use it
free fingerprints for detection

## Possible implementation
extract data locally from here https://ja4db.com/api/read/ periodically and query this data

### PR DESCRIPTION
**Pull request by g4ze**
closes #2361 

# Description

Please include a summary of the change and link to the related issue.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [x] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [x] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require any API key), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
    - [x] If the plugin interacts with an external service, I have created an attribute called precisely `url` that contains this information. This is required for Health Checks. 
    - [x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [x] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [x] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.
image
{
                "os": null,
                "notes": null,
                "device": null,
                "library": null,
                "verified": false,
                "application": null,
                "ja4_fingerprint": "t13d1517h2_8daaf6152771_b0da82dd1658",
                "ja4h_fingerprint": "ge11cn20enus_60ca1bd65281_ac95b44401d9_8df6a44f726c",
                "ja4s_fingerprint": null,
                "ja4t_fingerprint": null,
                "ja4x_fingerprint": null,
                "ja4ts_fingerprint": null,
                "observation_count": 1,
                "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
                "ja4tscan_fingerprint": null,
                "certificate_authority": null,
                "ja4_fingerprint_string": "t13d1517h2_002f,0035,009c,009d,1301,1302,1303,c013,c014,c02b,c02c,c02f,c030,cca8,cca9_0005,000a,000b,000d,0012,0017,001b,0023,0029,002b,002d,0033,4469,fe0d,ff01_0403,0804,0401,0503,0805,0501,0806,0601"
            },

### CODE REVIEW

**Comment by mlodic** [comment]
gtg, just migrations alignment. I'd do AdGuard -> ja4 -> goresym

**Comment by g4ze** [comment]
Cool! Any specific reasons on why that pattern?

**Comment by mlodic** [comment]
no reasons, just to help you with the migrations changes

**Comment by g4ze** [comment]
this can be merged merged after #2363

**Comment by g4ze** [comment]
we're gtg here @mlodic

**Review by mlodic — CHANGES_REQUESTED** [review]
sorry I forgot a comment appended

**Comment by mlodic** [comment]
honestly I am not supper happy with this implementation (see reasons in the docstring) but for now it could make sense.

We should probably rework all the analyzers that reads from local files. We should store them in a table and query the data from there

**Comment by g4ze** [comment]
ofcourse, that should be an ideal approach...
in the meanwhile, Ive asked [John](https://github.com/FoxIO-LLC/ja4?tab=readme-ov-file#ja4-was-created-by) if by any means, he has an approach for solid identification.
So can i consider this issue blocked for now?

**Comment by mlodic** [comment]
I would like to merge this anyway cause we in that way we have a basic analyzer available. Then, if we find other options with John, we could create a new PR with changes. What do you think?

**Comment by g4ze** [comment]
sure! sounds good to me.

**Pull request merged**
