### PR TITLE
[Analyzer] Netlas.io

### LINKED ISSUE #1258: [Analyzer] Netlas.io
## Name
Netlas.io

## Link
https://netlas.io/api

## Type of analyzer
* IP/domains search
* Generic search for other endpoints?

## Why should we use it
Free service with 2.5k requests per month. https://netlas.io/api
It is also possible to participate to their reward program here: https://netlas.io/alpha_release

### PR DESCRIPTION
**Pull request by deep-poharkar**
closes #1258

# Description
Add new analyzer netlas that scans IP and domains

## Type of change

- [x] New feature (non-breaking change which adds functionality).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook or ingestor) was added or changed, in which case:
    - [x] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](./Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook in `playbook_config.json`.
    - [ ] Check if it could make sense to add that analyzer/connector to other freely available playbooks.
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](./Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by deep-poharkar** [comment]
hey I think the method have changed since the last time. I am facing a problem when I try to create the migration file.

command used : `docker exec -ti intelowl_uwsgi python3 manage.py dumpplugin AnalyzerConfig Netlas`

error: 
```
/usr/local/lib/python3.9/site-packages/dnstwist.py:64 No module named 'selenium'

/usr/local/lib/python3.9/site-packages/dnstwist.py:82 [Errno 2] No such file or directory: b'/usr/local/lib/python3.9/site-packages/GeoLite2-Country.mmdb'

/usr/local/lib/python3.9/site-packages/dnstwist.py:86 No module named 'GeoIP'

/usr/local/lib/python3.9/site-packages/dnstwist.py:114 No module named 'ssdeep'

XLMMacroDeobfuscator: pywin32 is not installed (only is required if you want to use MS Excel)

Traceback (most recent call last):

  File "/opt/deploy/intel_owl/manage.py", line 25, in <module>

    main()

  File "/opt/deploy/intel_owl/manage.py", line 21, in main

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute

    output = self.handle(*args, **options)

  File "/opt/deploy/intel_owl/api_app/management/commands/dumpplugin.py", line 227, in handle

    content = self._migration_file(obj, serializer_class, app)

  File "/opt/deploy/intel_owl/api_app/management/commands/dumpplugin.py", line 166, in _migration_file

    obj_data, param_data, values_data = self._get_serialization(

  File "/opt/deploy/intel_owl/api_app/management/commands/dumpplugin.py", line 47, in _get_serialization

    obj_data = serializer_class(obj).data

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data

    ret = super().data

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data

    self._data = self.to_representation(self.instance)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 507, in to_representation

    for field in fields:

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 368, in _readable_fields

    for field in self.fields.values():

  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__

    res = instance.__dict__[self.name] = self.func(instance)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 356, in fields

    for key, value in self.get_fields().items():

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 1052, in get_fields

    field_names = self.get_field_names(declared_fields, info)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 1112, in get_field_names

    raise TypeError(

TypeError: The `exclude` option must be a list or tuple. Got str.



```

**Comment by 0ssigeno** [comment]
Uhm, let me check it, I probably fucked up something during the Ingestor change to the script

**Comment by 0ssigeno** [comment]
Yeah, typo, solve with cc54e7763448d08096ca956a34ccfd4023614053.
Can you rebase from develop and let me know if you are able to create the migration?

**Comment by deep-poharkar** [comment]
thank you its working fine now!

**Comment by 0ssigeno** [comment]
Perfect!
As for the code, lgtm, the only change that I would like to have is some sort of valid mockup inside the analyzer (instead of a plain `{}`). A response taken from their api docs, instead of using your own api key is enough.

That and the new migration for the `AnalyzerConfig`. After these 2 things, we can merge the PR.

**Comment by deep-poharkar** [comment]
> Perfect! As for the code, lgtm, the only change that I would like to have is some sort of valid mockup inside the analyzer (instead of a plain `{}`). A response taken from their api docs, instead of using your own api key is enough.
> 
> That and the new migration for the `AnalyzerConfig`. After these 2 things, we can merge the PR.

I added the mock response. But when I am trying to commit the changes the `black` is running for the migration files. 


```

error: cannot format api_app/ingestors_manager/migrations/0004_alter_ingestorreport_name.py: [Errno 13] Permission denied: 'api_app/ingestors_manager/migrations/0004_alter_ingestorreport_name.py'

error: cannot format api_app/analyzers_manager/migrations/0035_analyzer_config.py: [Errno 13] Permission denied: 'api_app/analyzers_manager/migrations/0035_analyzer_config.py'

```
Should I force commit or something?

**Comment by deep-poharkar** [comment]
> That and the new migration for the `AnalyzerConfig`. After these 2 things, we can merge the PR.

sorry but what do you mean by new migration?

**Comment by 0ssigeno** [comment]
Yeah, I should have added the thing about the permission.
When you are creating the migration inside the container, the file is created as `root:root`. If you go, in your host, inside `api_app/analyzers_manager/migration` you should be able to `chown` the file as your own, allowing the linter to correctly work.

**That** file is the migration file that it is missing in the PR: you should commit that too. And yes, it is correct the script it is not creating another migration because you already have made one for that `AnalyzerConfig`.

About the other params, as you wish. If you think that the user experience will benefit for having them, yes.

**Comment by deep-poharkar** [comment]
> About the other params, as you wish. If you think that the user experience will benefit for having them, yes.

They aren't much specified in the API docs. I was not able to test them.

**Review by 0ssigeno — CHANGES_REQUESTED** [review]
Two things:
1 - The analyzer retrieve from the api response this structure `result_data = result["items"][0]["data"]`. In the mockup that you added, this dictionary structure is missing. You should change the mock of the raw request (meaning that you should have the at least`items` and `data` keys) or you should change the parsing of the request because right now they are not compatible.
2 - Unfortunately, you have pushed your own key because it was present in the database. You can change the value in the migration from your own key to `None` and **revoke** the key inside Netlas.

The second step was a miscalculation on my side that allowed the dump of your private key instead of replacing them with a fake value. I will update the script to fix this behaviour

**Comment by deep-poharkar** [comment]
> 1 - The analyzer retrieve from the api response this structure `result_data = result["items"][0]["data"]`. In the mockup that you added, this dictionary structure is missing. You should change the mock of the raw request (meaning that you should have the at least`items` and `data` keys) or you should change the parsing of the request because right now they are not compatible.

will this work? 
the response looks like this
img

**Comment by deep-poharkar** [comment]
> 2 - Unfortunately, you have pushed your own key because it was present in the database. You can change the value in the migration from your own key to `None` and **revoke** the key inside Netlas.

I was about to ask about API key being visible in the migration file. I changed it to null like others

**Review by 0ssigeno — APPROVED** [review]
LGTM

**Comment by deep-poharkar** [comment]
The backend tests are failing. Is it due to my code?

**Comment by 0ssigeno** [comment]
Something wrong with the migration autogenerated, yey.
It is something on my end

**Comment by deep-poharkar** [comment]
Thanks @0ssigeno  I thought the` result` would more match the mock_response. nvm. Do let me know if there is anything else we need to change.

**Comment by 0ssigeno** [comment]
LGTM, waiting let's see if @mlodic  has some suggestions, otherwise I'm going to merge it

**Comment by mlodic** [comment]
The PR is good, we are just missing some points in the checklist regarding the documentation.

- [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.

- [ ]  [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/pull/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).

**Comment by deep-poharkar** [comment]
okay, I think I messed up. I pulled and rebase this changes and the develop branch as well.

**Comment by 0ssigeno** [comment]
No big deal, i'm going to squash all together anyway.

**Comment by 0ssigeno** [comment]
The review is for the docs part

**Review by mlodic — APPROVED** [review]

**Pull request merged**
