### PR TITLE
Remove whitespaces around =

### PR DESCRIPTION
**Pull request by ninoseki**
Remove whitespaces around `=` because it will produce the following error when executing `docker-compose up`.

```
$ docker-compose up
ERROR: In file /path/to/IntelOwl/env_file_app: environment variable name 'MOCK_CONNECTIONS ' may not contain whitespace.
```

### CODE REVIEW

**Comment by Eshaan7** [comment]
Thank you! But could you please make the same pull request against the `develop` branch ? We only push to the master branch for new releases.

**Comment by ninoseki** [comment]
@Eshaan7 Sorry, I should have to check the branching strategy before making this PR. 
I just changed the target branch to `develop`. Could you check it, please?

**Comment by Eshaan7** [comment]
Seems like your branch's history got quite messed up by changing the base branch :/
I am just about to push some changes to develop and If you don't mind, I could just push your change as well since it's just a one line change ?

Thank you for your contribution!

**Comment by ninoseki** [comment]
Ah,OK it makes sense for me.
Sorry for taking your time.

**Comment by Eshaan7** [comment]
It's no problem. Thank you for the bug report and resolution! You are welcome to contribute to the project in any way.

**Pull request closed without merging**
