### PR TITLE
Added ThreatFox Analyzer

### LINKED ISSUE #348: ThreatFox (from Abuse.ch) analyzer
There is this new great tool from Abuse.ch: https://threatfox.abuse.ch/api/

We should create a simple analyzer to check if an analyzed observables is in the threatfox database ("Search an IOC" query)

### PR DESCRIPTION
**Pull request by CITIZENDOT**
# Description

Added ThreatFox Analyzer

## Related issues
Closes #348 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [X] The pull request is for the branch develop
- [X] If I added a new analyzer, I updated the file [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md). If the analyzer provides additional optional configuration, I added the available options here: [Advanced-Usage](./Advanced-Usage.md)
- [ ] If I added external libraries/packages that use restrictive licenses, please add them in the [ReadMe - Legal Notice](https://github.com/certego/IntelOwl/blob/master/README.md) section
- [X] I added new secrets in the files [env_file_app_template](https://github.com/intelowlproject/IntelOwl/blob/master/env_file_app_template), [env_file_app_ci](https://github.com/certego/IntelOwl/blob/master/env_file_app_travis) and in the docs: [Installation](./Installation.md)
- [X] I have added tests in the [Tests](https://github.com/intelowlproject/IntelOwl/blob/master/tests) folder. 
- [ ] The tests gave 0 errors.
- [X] `Black` gave 0 errors.
- [X] `Flake` gave 0 errors.
- [X] I squashed the commits into a single one.
  
### please follow these rules
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review

# Real World Example
ThreatFox

### CODE REVIEW

**Review by mlodic — CHANGES_REQUESTED** [review]
hey @CITIZENDOT thank you for the PR!

However it seems that the work was done too fast, there are different errors! Please review the code, thanks!

**Comment by mlodic** [comment]
Honestly this PR was pretty unfair to other new recruits.

You just opened this after ~1 hour of the comment of another wannabe contributor [here](https://github.com/intelowlproject/IntelOwl/issues/348). So I told him/her that this work was already done and we did not need his/her help.

The point is that:
* you made a really fast PR. No checks, no nothing. We both know that you know how to do this PR correctly. It seems that you just pushed this PR really fast to have that new contributor out.
* I gently asked you to fix that but you made another unfinished work. 

This is unrespectful not only of that other contributor but also of the maintainers and all the community here.

I'll close this PR

**Comment by CITIZENDOT** [comment]
Sure @mlodic . I started working on it just the day before Shreyas commented. I thought, he might work on it, So, I pushed this to avoid multiple people working on same Issue. It's my mistake not to ask to assign this. 

Anyway, To welcome Shreyas, this PR could be a starting point to know how to add this analyzer.

**Comment by mlodic** [comment]
Ok but you should have said/written something.

Thank you for having explained that now.

**Pull request closed without merging**
