### PR TITLE
'soft_time_limit' added to 'configuration/analyzer_config.json'

### PR DESCRIPTION
**Pull request by Siddhant2510**
soft_time_limit for all keys in 'cofiguration/analyzer_config.json' has been added.

### CODE REVIEW

**Comment by mlodic** [comment]
Hi! Thank you for your contribution! :P Before merging, could you please squash all commits into a single one?
you can find the details of this fast procedure in the docs [here](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-squash-commits-to-a-single-one)

**Comment by Siddhant2510** [comment]
> Hi! Thank you for your contribution! :P Before merging, could you please squash all commits into a single one?
> you can find the details of this fast procedure in the docs [here](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-squash-commits-to-a-single-one)

Thank you for making me aware of how can I improve my contribution. I hope now it is good to merge.

**Review by Eshaan7 — CHANGES_REQUESTED** [review]
Spacing should be of size 2 and not 8.

**Review by Eshaan7 — APPROVED** [review]

**Comment by Eshaan7** [comment]
Thankyou for your contribution, @Siddhant2510 !

**Pull request merged**
