### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by PolarBearGod**
# Description

Updated the instructions for the following values:

* In the "lazy" TL;DR section (and the deployment guide further down) I added the line to make a copy of the `.env` file and drop it into the root IntelOwl directory. This was causing a failure to set the correct Docker Image tag and ultimately failing everything.   
(`WARNING: The INTELOWL_TAG_VERSION variable is not set. Defaulting to a blank string.`)   
(`ERROR: something something - latest not found: manifest unknown: manifest unknown`)
* Added the `build` command to set the environment as it was creating the warning error above and not completing.
* Changed instances of `python start.py....` to `python3 start.py....` as some Linux images come with Python 2.7 installed by default, which will cause the script to fail.

## Related issues
Out of the box installation (otherwise known as fresh installations) will fail given the current directions.

## Type of change

Please delete options that are not relevant.
- [✔️] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [✔️] The pull request is for the branch develop
- The below are not applicable to this pull request.
- [❌] If I added a new analyzer, I updated the file [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md). If the analyzer provides additional optional configuration, I added the available options here: [Advanced-Usage](./Advanced-Usage.md)
- [❌] If I added external libraries/packages that use restrictive licenses, please add them in the [ReadMe - Legal Notice](https://github.com/certego/IntelOwl/blob/master/README.md) section
- [❌] I added new secrets in the files [env_file_app_template](https://github.com/intelowlproject/IntelOwl/blob/master/docker/env_file_app_template), [env_file_app_ci](https://github.com/certego/IntelOwl/blob/master/docker/env_file_app_ci) and in the docs: [Installation](./Installation.md)
- [❌] I have added tests in the [Tests](https://github.com/intelowlproject/IntelOwl/blob/master/tests) folder. 
- [❌] The tests gave 0 errors.
- [❌] `Black` gave 0 errors.
- [❌] `Flake` gave 0 errors.
- [❌] I squashed the commits into a single one. (optional, they will be squashed anyway by the maintainer)

### CODE REVIEW

**Comment by mlodic** [comment]
thank you very much for your interest in the project and the help in critical problems like the documentation.

I have some questions for you:
* I cannot replicate the problem about the missing .env file. Are you sure that you have the latest IntelOwl version? The `.env` file should be in the `docker` folder. Before v.2.0.0 it was in the root folder of the project.
* the `python3 start.py prod build` is not needed because if you do not have the existing images, `up` would just build them for you. `build` is required only if you have to update the current images. See [update](https://intelowl.readthedocs.io/en/latest/Installation.html#update-to-the-most-recent-version)

I assume this could be a problem related to something broken caused by breaking changes introduced in IntelOwl in the v2.0.0.
If you prune the IntelOwl docker images and you try to install IntelOwl in a clean environment, you should not face those problems. Please let me know when you got some time.

**Comment by PolarBearGod** [comment]
Hi @mlodic!

I am a bit of a freak when it comes to projects. Everything gets its own little box, so I stood up a fresh image of Ubuntu 18.04 LTS. 

1. I installed `docker`, `docker-compose`, and `python3.8` (as well as `python3-pip` but that is kinda irrelevant). 
2. Following along the documentation, I performed a `git clone` into my user's home directory and made the required modifications. 
3. I went to use `python start.py prod up` It gave me an invalid syntax error that is presented when running an older version of Python on a Python 3+ script. I adjusted for that (by using `python3 start.py....`) the script successfully ran BUT I was presented the errors in this commit. 
4. The issue was only resolved when I made a copy of the `.env.` file and dropped it into the root project folder (`cp ~/IntelOwl/docker/.env ~/IntelOwl/.env`). 
5. Once done, the `up` command gave an error saying there was no image found or something another. I looked at the docs and it showed a `build` command. 
6. After successfully building, I was able to run the full `python3 start.py prod up` command getting a successful web interface.

I did notice there was a closed issue that was raised back in January of someone that ran into the same issue. While they were rather rude about the issue, I was experiencing the same problems described.

**Comment by mlodic** [comment]
This is all extremely useful. The point is that I still think that the cause is something in your environment, in particular the docker-compose version (for instance they fixed a bug [here](https://docs.docker.com/compose/release-notes/#1231) about the `--project-directory` option that the `start.py` script leverage to find the `.env` file + this other change [here](https://docs.docker.com/compose/release-notes/#bug-fixes-20))

Could you please just check the version of docker and docker-compose? and if they match at least the versions stated in the [docs here](https://intelowl.readthedocs.io/en/latest/Installation.html#requirements)? 

If we get the accurate cause, we can address it the best way in both the docs and the project. Thank you in advance

**Comment by PolarBearGod** [comment]
Hmmm seems the `docker-compose` from the Bionic Universe is out of date. My apologies! If you would like to reject this `pull` by all means.

```
username@UBUNTU18OWLTEST:~/IntelOwl$ sudo docker --version  
Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.2  
```

```
username@UBUNTU18OWLTEST:~/IntelOwl$ sudo docker-compose version  
docker-compose version 1.17.1, build unknown  
docker-py version: 2.5.1  
CPython version: 2.7.17  
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018  
```

```
username@UBUNTU18OWLTEST:~/IntelOwl$ sudo apt install docker-compose
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker-compose is already the newest version (1.17.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
username@UBUNTU18OWLTEST::~/IntelOwl$ cat /etc/os-release                                                             
NAME="Ubuntu"   
VERSION="18.04.5 LTS (Bionic Beaver)"   
ID=ubuntu  
ID_LIKE=debian  
PRETTY_NAME="Ubuntu 18.04.5 LTS"  
VERSION_ID="18.04"  
HOME_URL="https://www.ubuntu.com/"  
SUPPORT_URL="https://help.ubuntu.com/"  
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" 
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"  
VERSION_CODENAME=bionic  
UBUNTU_CODENAME=bionic  
```

**Comment by mlodic** [comment]
The docker-compose version is really old. Please try to install the most recent one from [here](https://docs.docker.com/compose/install/) and let me know. If I was right then, I can accept your PR without the part of `cp .env ../.env` and `python3 start.py prod build` (also this could be related to the version).

Anyway, I guess I will also add something more clear about the requirements to avoid this problems. For instance, I could move the "Requirements" section before the "TL;DR".

**Comment by PolarBearGod** [comment]
Was able to manually add in `docker` and `docker-compose` and have confirmed I have the latest and greatest.

```
username@collection-machine:~/IntelOwl$ sudo docker-compose --version  
docker-compose version 1.29.1, build c34c88b2  
username@collection-machine:~/IntelOwl$ sudo docker --version  
Docker version 20.10.6, build 370c289  
```

When attempting to run the start script as is:

``` 
username@collection-machine:~/IntelOwl$ sudo python start.py prod up
sudo: python: command not found

username@collection-machine:~/IntelOwl$ python start.py prod up

Command 'python' not found, but can be installed with:

sudo apt install python3
sudo apt install python
sudo apt install python-minimal

You also have python3 installed, you can run 'python3' instead.
```

Once I run the script with `python3` everything kicks in and starts without a hitch.

**Comment by sp35** [comment]
@PolarBearGod You can use a virtual environment with python3 or add an alias for `python3` as `python`. This way whenever you refer to `python`, it would run using `python3`.

**Comment by PolarBearGod** [comment]
@sp35 I feel you but keeping in mind the spirit of the "Read The Docs". If you are saying that the user should have an alias for it or to change their `paths` or anything else, then that should be listed in the docs. 

What I will do is kill this pull and make the notes in an issue and close it. From a build perspective, it is assumed we are starting at ground zero. It is absolutely on me for not 100% validating that the "Bionic Universe" was installing the correct versions but I would beg that I am surely not the only one that ran into this. Alternatively, for those that do run into the issues described here there is recourse for them documented in an issue versus a pull request..

**Comment by sp35** [comment]
I agree with you, we should mention the versions in a requirements section.

**Pull request closed without merging**
