### PR TITLE
hudsonrock

### LINKED ISSUE #2027: [Analyzer] HudsonRock
## Name
HudsonRock

## Link
https://www.hudsonrock.com/

## Type of analyzer
domain: domain intelligence
ip: ip intelligence
generic: end user protection (email lookup)

## Why should we use it
free quota with the free api key provided at: https://cavalier.hudsonrock.com/docs

## Possible implementation
follow the docs:
https://cavalier.hudsonrock.com/docs

### PR DESCRIPTION
**Pull request by g4ze**
closes #2027 and #2279

# Description

add hudsonrock anakyzer
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [x] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [x] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [x] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results. 
    - [x] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [x] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.
image
 {
                            "date_uploaded": "2019-11-07T04:38:32.024Z",
                            "stealer_family": "Vidar",
                            "antiviruses": "Not Found",
                            "employee_session_cookies": "null",
                            "date_compromised": "2019-11-04T13:33:47.000Z",
                            "credentials": [
                                {
                                    "type": "client",
                                    "url": "••••••••••••••",
                                    "domain": "disney.com",
                                    "username": "•••••••",
                                    "password": "••••••••",
                                }
                            ],
                            "stealer": "••••••••••••",
                            "employeeAt": ["••••••••••"],
                            "clientAt": [
                                "•••••••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "•••••••••",
                                "•••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "•••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••••••••",
                                "•••••••••",
                                "•••••••••••••",
                                "••••••••",
                                "••••••••••••••••",
                                "••••••••••",
                                "••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "•••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••",
                                "•••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••",
                                "••••••••••••",
                                "••••••••",
                                "••••••••••",
                                "•••••••",
                                "•••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••••••",
                                "••••••",
                                "••••••••••",
                                "••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••",
                                "•••••••••••",
                                "••••••",
                                "•••••••••",
                                "•••••••••",
                                "••••••••••",
                                "•••••••••••••••",
                            ],
                            "ip": "••••••••••••••",
                            "malware_path": "••••••••••••••",
                        },
                        {
                            "date_uploaded": "2019-11-06T21:51:35.676Z",
                            "stealer_family": "Vidar",
                            "antiviruses": "Not Found",
                            "employee_session_cookies": "null",
                            "date_compromised": "2019-11-03T20:39:11.000Z",
                            "credentials": [
                                {
                                    "type": "client",
                                    "url": "•••••••••••••••",
                                    "domain": "disney.com",
                                    "username": "•••",
                                    "password": "•••••••••",
                                }
                            ],
                            "stealer": "••••••••••••••••••••••••••••••••",
                            "employeeAt": ["•••••••••••", "••••••••••", "••••••"],
                            "clientAt": [],
                            "ip": "•••••••••••••",
                            "malware_path": "•••••••••••••••••••",
                        },
                        {
                            "date_uploaded": "2021-07-11T12:17:51.429Z",
                            "stealer_family": "RedLine",
                            "computer_name": "This PC",
                            "operating_system": "Windows 10 Home x64",
                            "antiviruses": "Norton 360",
                            "employee_session_cookies": "null",
                            "date_compromised": "2021-07-06T23:27:32.000Z",
                            "credentials": [
                                {
                                    "type": "client",
                                    "url": "••••••••",
                                    "domain": "disney.com",
                                    "username": "••••••",
                                    "password": "••••••••••",
                                }
                            ],
                            "stealer": "•••••••••••••••••••",
                            "employeeAt": ["•••••••••", "••••••••", "••••••••••"],
                            "clientAt": [
                                "•",
                                "•",
                                "••••",
                                "••••••••••••••",
                                "•••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "•••••••••",
                                "••••••••••••",
                                "•••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••••",
                                "••••••••••••",
                                "••••••••••",
                                "••••••••••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "••••••••",
                                "•••••••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••••••••••",
                                "•••••••••••••••••••",
                                "••••••••••••••••••••",
                                "•••••••••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••••••••••",
                                "•••••••••••••••••••••••",
                                "••••••••",
                                "••••••••••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "••••••••••••••",
                                "••••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "••••••••••",
                                "••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••",
                                "•••••••••••",
                                "•••••••",
                                "•••••••",
                                "••••••••••",
                                "••••••",
                                "••••••••",
                                "••••••••••",
                                "••••••••••••••••",
                                "••••••••••••",
                                "•••••••",
                                "•••••••••••••••",
                                "••••••••••",
                                "••••••••••••••••••",
                                "•••••••",
                                "••••••••",
                                "•••••••",
                                "•••••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "••••••••••••••••",
                                "•••••••••••",
                                "•••••••••••",
                                "•••••••••••••••",
                                "•••••••••••",
                                "•••••••",
                                "•••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••••••",
                                "••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "••••••••",
                                "••••••••••••••",
                                "•••••••••••",
                                "•••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••",
                                "•••••••",
                                "•••••••••",
                                "••••••••••••",
                                "•••••••••••••••",
                                "•••••••••••••••",
                                "•••••••••",
                                "•••••••••••",
                                "••••••••",
                                "•••••••••••",
                                "••••••••••••••",
                                "•••••••••••",
                                "••••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••",
                                "••••••••",
                                "•••••••••••",
                                "•••••••••••",
                                "••••••••••••••••",
                                "•••",
                                "••••••••",
                                "•••••••••",
                            ],
                            "ip": "••••••••••••••",
                            "malware_path": "•••••••••••••",
                        },
                        {
                            "date_uploaded": "2021-05-06T05:58:56.299Z",
                            "stealer_family": "RedLine",
                            "computer_name": "jskho",
                            "operating_system": "Windows 10 Home x64",
                            "antiviruses": "Norton Security",
                            "employee_session_cookies": "null",
                            "date_compromised": "2021-05-06T01:31:09.000Z",
                            "credentials": [
                                {
                                    "type": "client",
                                    "url": "•••••••••••••••••",
                                    "domain": "disney.com",
                                    "username": "•••••••@gmail.com",
                                    "password": "••••••••",
                                }
                            ],
                            "stealer": "•••••••••••••••",
                            "employeeAt": [],
                            "clientAt": [
                                "••••••••••••••",
                                "•••••••••••••••••••",
                                "•••••••••••",
                                "•",
                                "•",
                                "••••",
                                "••••••••••••••••",
                                "••••••••••••••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••",
                                "••••••••••",
                                "•••••••••••••••",
                                "•••••••••",
                                "•••••",
                                "••••••••••••",
                                "•••••••••••••",
                                "••••••••••••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••",
                                "•••••••••",
                                "••••••••••••••",
                                "••••••",
                                "••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••",
                                "•••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••",
                                "•••••••••••••••••••",
                                "•••••••••••••••••••",
                                "••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "•••••••••",
                                "•••••••••••••••••••••",
                                "•••••••••••••••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••••••••••••••••",
                                "•••••••••••••",
                                "•••••••",
                                "••••••••••••••",
                                "••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "•••••••••",
                                "••••••••",
                                "••••••",
                                "••••••",
                                "•••••••••••",
                                "•••••••••••••••••••",
                                "•••••••••••••••",
                                "••••••••••",
                                "•••••••••••••••••",
                                "••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "••••••",
                                "••••••••••",
                                "••••••••••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "•••••••••••••",
                                "••••••••••••••••••••",
                                "•••••",
                                "••••••••",
                                "•••••••••••",
                                "••••••••••••••",
                                "•••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••",
                                "••••••••••",
                                "••••••••••",
                                "••••••••••••••••",
                                "••••••••",
                                "•••••••••",
                                "••••••••••",
                                "•••••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "••••••••••••••",
                                "••••••••",
                                "•••••••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "•••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••••••••",
                                "•••••••••",
                                "••••••••••••••",
                                "•••••••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••",
                                "•••••••••••••••••••••••••",
                                "•••••••••••",
                                "••••••••••••",
                                "••••••••••••••",
                                "•••••••••",
                                "••••••••",
                                "••••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••",
                                "•••••••••••••",
                                "••••••••••",
                                "•••••••••••••",
                                "•••••••••••••",
                                "••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••",
                                "•••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••",
                                "••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "••••••••••••",
                                "••••••••••••••••••••••",
                                "•••••••••",
                                "•••••••••••••••••••••",
                                "••••••••••••••",
                                "•••••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "•••••••••••",
                                "•••••••••••••••••••",
                                "••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••",
                                "••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••••••••",
                                "••••••••••••",
                                "•••••••••••",
                                "••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••••••",
                                "•••••••••••••",
                                "•••••••••••••••",
                                "••••••••",
                                "••••••••••",
                                "•••••••••••••••••••••",
                                "•••••••••",
                                "•••••••••••",
                                "•••••••••••••••",
                                "•••••••••••",
                                "•••••••",
                                "••••••••",
                                "••••••••",
                                "•••••••••",
                                "•••••••••••••••",
                                "••••••••••••••••",
                                "••••••••••••••••••",
                                "•••••••••",
                                "••••••••••••••••",
                                "•••••••",
                                "•••",
                            ],
                            "ip": "•••••••••••••",
                            "malware_path": "••••••",
                        },
                        {
                            "date_uploaded": "2021-04-02T11:46:34.357Z",
                            "stealer_family": "RedLine",
                            "computer_name": "samih",
                            "operating_system": "Windows 10 Home x64",
                            "antiviruses": "Windows Defender",
                            "employee_session_cookies": "null",
                            "date_compromised": "2021-03-31T18:23:31.000Z",
                            "credentials": [
                                {
                                    "type": "client",
                                    "url": "",
                                    "domain": "disney.com",
                                    "username": "••••••••",
                                    "password": "••••••••••",
                                },
                                {
                                    "type": "client",
                                    "url": "•••••••••••••••••",
                                    "domain": "disney.com",
                                    "username": "••••••••",
                                    "password": "••••••••••",
                                },
                            ],
                            "stealer": "••••••••••••••••••••",
                            "employeeAt": [],
                            "clientAt": [
                                "•",
                                "•",
                                "••••",
                                "•••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••••••••••",
                                "••••••••••",
                                "•••••••••••",
                                "••••••",
                                "••••••••",
                                "••••••••••••",
                                "••••••••••",
                                "•••••••••",
                                "•••••••••••••••••••",
                                "••••••••••••••••••",
                                "••••••••••••",
                                "••••••••••",
                                "••••••••••",
                                "••••••••••",
                                "•••••••••••••••••",
                                "••••••••••",
                                "•••••••••••••",
                                "••••••••",
                                "••••••••••••••••••••••••••••",
                                "••••••••••••••••",
                                "•••••••••",
                                "•••",
                            ],
                            "ip": "••••••••••••••",
                            "malware_path": "•••••",
                        },

### CODE REVIEW

**Comment by g4ze** [comment]
hey! @mlodic  can you please check the wrapper and let me know if it needs work?

**Comment by mlodic** [comment]
like they specified, in the `generic` option we could detect if that's an email and, in case, use the correct API too

**Comment by mlodic** [comment]
then, it would make sense to support the majority of the parameters available for the queries and not only the 2 ones you added: https://cavalier.hudsonrock.com/docs

**Comment by g4ze** [comment]
> like they specified, in the generic option we could detect if that's an email and, in case, use the correct API too

Do you mean that we should validate if the generic entered is an email or not an only then proceed to run the api?

**Comment by mlodic** [comment]
yes and no: the `generic` type functions as a container for anything so the analyzer should differentiate between what he gets and run a different api call based on the content it receives

**Comment by g4ze** [comment]
okay, pls correct me if I'm wrong here, the `generic` type in our case is required to only for the logon/email endpoint right?
We just need to:
```
if observabletype is generic and is email:
  run login api endpoint
```

**Comment by g4ze** [comment]
`else: a config err`

**Comment by g4ze** [comment]
review pls

**Comment by g4ze** [comment]
also, a `clear` tlp for this makes sense right?

**Comment by mlodic** [comment]
seems good to me, just the maximum TLP should be `AMBER` -> This value can be quite confusing to set. In this case this should be amber because it is an external service so TLP:RED must esclude any external connection, while all the other TLP values allow them-.

**Comment by g4ze** [comment]
I think I understand what you are saying. Is there any doc which I can refer to, which elaborates on TLP. It's a bit too confusing atm

**Comment by mlodic** [comment]
https://intelowl.readthedocs.io/en/latest/Usage.html#tlp-support

**Comment by g4ze** [comment]
how do i decide the privacy factor? using an external api/tool is considered as an impact on privacy?

**Comment by g4ze** [comment]
I think we're gtg here.

**Comment by mlodic** [comment]
> using an external api/tool is considered as an impact on privacy?

yep cause you are sending your data to an external service so it should be excluded for TLP:RED

**Pull request merged**
