### PR TITLE
Update censys.io, Closes #439

### LINKED ISSUE #439: Update Censys.io analyzer to v2
Censys data can enrich many security products and platforms.

#### Endpoint
- Get structured data about a specific host or website. https://censys.io/api/v1/docs/view

### PR DESCRIPTION
**Pull request by g4ze**
Closes #439
# Description

Upgraded the censys api endpoint to v2
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [x] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

image
Raw Json:
{'code': 200, 'status': 'OK', 'result': {'ip': '190.121.56.10', 'services': [], 'location': {'continent': 'South America', 'country': 'Chile', 'country_code': 'CL', 'city': 'Osorno', 'postal_code': '5290000', 'timezone': 'America/Santiago', 'province': 'Los Lagos Region', 'coordinates': {'latitude': -40.57395, 'longitude': -73.13348}}, 'location_updated_at': '2024-01-27T14:52:11.775086600Z', 'autonomous_system': {'asn': 14117, 'description': 'Telefonica del Sur S.A.', 'bgp_prefix': '190.121.56.0/21', 'name': 'Telefonica del Sur S.A.', 'country_code': 'CL'}, 'autonomous_system_updated_at': '2024-01-27T14:52:11.775086600Z', 'last_updated_at': '2023-04-30T00:04:14.886Z'}}

### CODE REVIEW

**Comment by g4ze** [comment]
@mlodic made required changes. I guess we are done. However I do have one small doubt. In the `DeepSource: Python` workflow check, why does it always asks to override the `update` function? There seems to be no use of always overriding the update function and as per my observation, update function has not been overridden in most of the analyzers and they still seem to work well.

**Comment by mlodic** [comment]
yes, that `update` function has been added recently in the framework. This is the reason why most of the analyzers do not have that function declared. Deepsource is right about it because that is an abstract method and clean practices wants that this method should always be explicitly overwritten. In practice, that does not change anything so well, that's ok either way.

Before merging the PR, could you please add the example of the results in the MockUpResponse? That is something that I recently add to the PR request template but that does not appear in this PR template cause that is not in `master` yet.
That helps us to maintain a more consistent test and to keep a record of the possibile results of the services in the code. ty

**Comment by g4ze** [comment]
About the MockUpResponse: There's an issue wherein the json mockup gets formatted by the `black` lint pre-commit. The formatted file attains a state where it has got some lines in the mockup response that are too long to pass the `flake8` pre-commit. This puts us in stuck in loop situation, where `black` formats the file and `flake8` deems a line too long. A possible fix could be deleting some longer fields of the `MockUpResponse` or have a different folder created to store all the mockupresponses and make `flake8` ignore it.

**Comment by g4ze** [comment]
Don't mind the previous comment, I just had to store the mock json in a variable; all good

**Pull request merged**
