### PR TITLE
Polyswarm analyzer closes#1255

### PR DESCRIPTION
**Pull request by g4ze**
# Description

Please include a summary of the change and link to the related issue.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [x] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [x] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [x] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [x] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require any API key), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [x] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
    - [ ] If the plugin interacts with an external service, I have created an attribute called precisely `url` that contains this information. This is required for Health Checks. 
    - [x] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [x] I have added that raw JSON sample to the `MockUpResponse` of the `_monkeypatch()` method. This serves us to provide a valid sample for testing.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.
- [x] After you had submitted the PR, if `DeepSource`, `Django Doctors` or other third-party linters have triggered any alerts during the CI checks, I have solved those alerts.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by mlodic** [comment]
is this still a draft?

**Comment by g4ze** [comment]
Facing the same problem I did on domain check and knockpy.

**Comment by g4ze** [comment]
I think this problem only arises when I'm implementing analysers that use new libraries or packages.

**Comment by mlodic** [comment]
are you rebuilding the container after you change the requirements?

**Comment by g4ze** [comment]
yes I am, I'll redo it and update you again.

**Comment by g4ze** [comment]
`result: {'assertions': [{'engine': 'Qihoo 360', 'asserts': 'Benign'}, {'engine': 'Kaspersky', 'asserts': 'Benign'}, {'engine': 'XVirus', 'asserts': 'Benign'}, {'engine': 'SecureAge', 'asserts': 'Benign'}, {'engine': 'Electron', 'asserts': 'Benign'}, {'engine': 'Proton', 'asserts': 'Benign'}, {'engine': 'Filseclab', 'asserts': 'Benign'}, {'engine': 'DrWeb', 'asserts': 'Benign'}, {'engine': 'Alibaba', 'asserts': 'Benign'}, {'engine': 'SecondWrite', 'asserts': 'Benign'}, {'engine': 'ClamAV', 'asserts': 'Benign'}, {'engine': 'Ikarus', 'asserts': 'Benign'}, {'engine': 'NanoAV', 'asserts': 'Benign'}], 'positives': 0, 'total': 13, 'PolyScore': 0.33460048640798623, 'sha256': '50f4d8be8d47d26ecb04f1a24f17a39f3ea194d8cdc3b833aef2df88e1ce828b', 'md5': '76deca20806c16df50ffeda163fd50e9', 'sha1': '99ff1cd17aea94feb355e7bdb01e9f788a4971bb', 'extended_type': 'GIF image data, version 89a, 821 x 500', 'first_seen': datetime.datetime(2024, 7, 27, 20, 20, 12, 121980), 'last_seen': datetime.datetime(2024, 8, 7, 9, 44, 21, 975401), 'permalink': 'https://polyswarm.network/scan/results/file/50f4d8be8d47d26ecb04f1a24f17a39f3ea194d8cdc3b833aef2df88e1ce828b/45136234696914602'}`

**Comment by g4ze** [comment]
lmk the migration sequence for once we are ready. Also i think the previous problem was something related to docker build cache and my ISP. All good now.

**Comment by mlodic** [comment]
polyswarm -> knock so you can finish this while you are here

**Comment by g4ze** [comment]
i've updated the pr, kindly review. do check the TLP.

**Review by mlodic — COMMENTED** [review]
for file analysis this is great!

Are you also able to implement the analyzer for observables, like stated in the issue description?

```
Hash search
IOC search -> domains/IP addresses
```

**Comment by g4ze** [comment]
ah my bad! on it!

**Comment by g4ze** [comment]
image
i think the free tier doesnt allow usage of ioc endpoints. hashes seem to be working tho.

**Comment by mlodic** [comment]
oki, I think you can keep them both and we write in the analyzer description that that specific endpoint is for paid customers only. ty!

**Comment by g4ze** [comment]
image
for hashes

**Comment by mlodic** [comment]
there is an error in the CI, after that I'll merge it! great work!

**Comment by g4ze** [comment]
seems gtg @mlodic

**Review by mlodic — APPROVED** [review]

**Pull request merged**
