### PR TITLE
Multiline config for plugin

### LINKED ISSUE #1826: Allow multiline value in PluginConfig
This is useful for secrets like private key and certificates.

### PR DESCRIPTION
**Pull request by shivam-Purohit**
closes #1826

# Description

Add multiline support for the plugin config.

## Type of change

- [x] New feature (non-breaking change which adds functionality).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector, visualizer, playbook, pivot or ingestor) was added or changed, in which case:
    - [ ] I strictly followed the documentation ["How to create a Plugin"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-plugin)
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] I have dumped the configuration from Django Admin using the `dumpplugin` command and added it in the project as a data migration. (["How to share a plugin with the community"](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-share-your-plugin-with-the-community))
    - [ ] If a File analyzer was added and it supports a mimetype which is not already supported, you added a sample of that type inside the archive `test_files.zip` and you added the default tests for that mimetype in [test_classes.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_classes.py).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook by following [this guide](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-modify-a-plugin).
    - [ ] Check if it could make sense to add that analyzer/connector to other [freely available playbooks](https://intelowl.readthedocs.io/en/develop/Usage.html#list-of-pre-built-playbooks).
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [x] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved (see `tests` folder). All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Contribute.md)).
- [x] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by shivam-Purohit** [comment]
@mlodic I tried debugging the previous error it seems like error is due to data is not json compliant. 
The value i am passing is something like this
`"shivam purohit\nvalue"`
When it tries to load this data into json using json.load
it fails and send back error it is mostly because of the newline character
i tried to dump it into json which converts this into json formatted string
and then again try to load it into json.
it works for now, as it saves the config for now 
but also show error but if i reload the page it saves and allow me to edit it 
sometimes show data saved successfully ( its not consistent )
ubuntuMachine  Running  - Oracle VM VirtualBox 20-02-2024 19_46_38

**Review by drosetti — CHANGES_REQUESTED** [review]
I found bugs:

* Every time you edit and save the text will be wrapped with other `"` 
* If you try to set: analyzer -> classic_dns -> query_type -> AAAA (or nay other value) in the run configuration in the start scan there will be the value `"\""`.
* I tried to add in a string field something like `test line \n another line` and it doesn't  is present in the runtime configuration.

**Comment by shivam-Purohit** [comment]
This is how we want right?
Screenshot from 2024-03-09 21-24-45

PTAL after making a multiline config this is how it might look.
Screenshot from 2024-03-09 21-26-27


Screenshot from 2024-03-09 21-26-13


If you think this is correct I'll move forward.

**Comment by mlodic** [comment]
it makes sense to me

**Comment by drosetti** [comment]
I agree with Matteo, this is the UX I had in my mind.

**Comment by aryan-bhokare** [comment]
> I agree with Matteo, this is the UX I had in my mind.

I'll make the commit then

**Comment by shivam-Purohit** [comment]
@drosetti PTAL

**Pull request merged**
