### PR TITLE
Added LinkedIn release action

### LINKED ISSUE #1299: Script to automate release on LinkedIn
It would be super cool to have a Github Action that we could use and also share with the community to share a linkedin post after a release. https://www.linkedin.com/company/86657205

### PR DESCRIPTION
**Pull request by abheektripathy**
closes #1299.
# Description

Added a gh action to run on every new release, which first generates an access token using secrets `LINKEDIN_CLIENT_ID` and `LINKEDIN_CLIENT_SECRET` , then on it's success posts to linkedIn with the newest release and lastly returns the post url.

## Type of change

- [x] New feature (non-breaking change which adds functionality).

# Checklist

- [x] I have read and understood the rules about [how to Contribute](https://intelowl.readthedocs.io/en/latest/Contribute.html) to this project
- [x] The pull request is for the branch `develop`
- [ ] A new plugin (analyzer, connector or playbook) was added or changed, in which case:
    - [ ] [Usage](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/Usage.md) file was updated.
    - [ ] [Advanced-Usage](./Advanced-Usage.md) was updated (in case the plugin provides additional optional configuration).
    - [ ] If the plugin requires mocked testing, `_monkeypatch()` was used in its class to apply the necessary decorators.
    - [ ] If a File analyzer was added, its name was explicitly defined in [test_file_scripts.py](https://github.com/intelowlproject/IntelOwl/blob/master/tests/analyzers_manager/test_file_scripts.py) (not required for Observable Analyzers).
    - [ ] If you created a new analyzer and it is free (does not require API keys), please add it in the `FREE_TO_USE_ANALYZERS` playbook in `playbook_config.json`
    - [ ] I have provided the resulting raw JSON of a finished analysis and a screenshot of the results.
- [ ] If external libraries/packages with restrictive licenses were used, they were added in the [Legal Notice](https://github.com/certego/IntelOwl/blob/master/.github/legal_notice.md) section.
- [ ] Linters (`Black`, `Flake`, `Isort`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved. All the tests (new and old ones) gave 0 errors.
- [ ] If changes were made to an existing model/serializer/view, the docs were updated and regenerated (check [CONTRIBUTE.md](./Contribute.md)).
- [ ] If the GUI has been modified:
    - [ ] I have a provided a screenshot of the result in the PR.
    - [ ] I have created new frontend tests for the new component or updated existing ones.

### Important Rules
- If you miss to compile the Checklist properly, your PR won't be reviewed by the maintainers.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem
- Everytime you make changes to the PR and you think the work is done, you should explicitly ask for a review. After being reviewed and received a "change request", you should explicitly ask for a review again once you have made the requested changes.

### CODE REVIEW

**Comment by abheektripathy** [comment]
@mlodic i have used [Article Share Api](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin#create-an-article-or-url-share:~:text=Create%20an%20Article%20or%20URL%20Share) to fetch the preview image that comes with the link. 
Would it be better to switch to the [Text share Api](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin#create-an-article-or-url-share:~:text=No-,Create%20a%20Text%20Share,-The%20example%20below), if that's possible with this?

also, should I use repo secrets to get the person urn?

**Comment by mlodic** [comment]
hey @abheektripathy! thank you for your work!

did you have any chance to try this script in any way? maybe with your linkedin profile?
if not, I could merge it in a dedicated branch, change momentarily the trigger and try it out! And I could give you access with write permissions so you can continue the work there.

about the Article Share API: that is cool and better than the Text Share API!

about the person urn, [here](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin#request-body-schema) they say that it is possible to get it. Could you check it out?

**Comment by abheektripathy** [comment]
hey @mlodic I tried to use this script with one of my apps ([workflow run here](https://github.com/abheektripathy/Rantman/actions/runs/4843007116/jobs/8710557407)), it wasn't able to generate the access token, did some research ([based on this](https://stackoverflow.com/questions/64619387/how-to-call-the-linkedin-api-using-python#:~:text=Below%20is%20a%20second%20solution%20valid%20only%20if%20your%20application%20is%20a%20part%20of%20LinkedIn%20Developer%20Enterprise%20Products%20paid%20subscription%2C%20also%20then%20you%20need%20to%20Enable%20Client%20Credentials%20Flow%20in%20your%20application%20settings%2C%20next%20steps%20uses%20so%2Dcalled%202%2DLegged%20OAuth%202.0%20Authentication%3A)) then to find, we can only use [2-Legged-Auth](https://learn.microsoft.com/en-us/linkedin/shared/authentication/client-credentials-flow?context=linkedin%2Fconsumer%2Fcontext) only if your application is a part of LinkedIn Developer Enterprise Products paid subscription.
For free applications we have to use [3-Legged-Auth](https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin%2Fcontext&tabs=HTTPS1#step-2-request-an-authorization-code) which wouldn't be able to handle redirects as a browser, plus there's no way to capture the access token then, from a CI environment.

We can generate an access token [manually](https://www.linkedin.com/developers/tools/oauth) though which would expire, but then we would have to update them in repo secrets everytime.
Even if we use [refresh tokens](https://learn.microsoft.com/en-us/linkedin/shared/authentication/programmatic-refresh-tokens?context=linkedin%2Fcontext), we'll still have to update the repo secret with the newly generated access token.
so it kinda defeats the purpose of automating it.
How should i proceed with this then?

**Comment by abheektripathy** [comment]
you are right, giving an action write perms to repo secrets wouldn't be safe. A workflow for automating linkedIn posts seems like a cool thing to have but the as of now, i believe, its not worth the work here.
Im closing this PR here.

we can keep the issue open though, if someone from the community finds a solution for this. Though seems highly unlikely seeing its the LinkedIn API's perms for free applications itself that's the bottleneck here.

**Pull request closed without merging**
