### PR TITLE
Upgraded capa to version 1.1.0

### PR DESCRIPTION
**Pull request by 0ssigeno**
This pr should resolve issue #141

### CODE REVIEW

**Comment by Eshaan7** [comment]
Thankyou for your contribution. However, the test for Capa is only a mock test. Could you please include a screenshot of running the updated capa container and starting an analysis with it ? To test that nothing broke.

**Comment by mlodic** [comment]
They have also just released capa v.1.2.0 lol

**Comment by 0ssigeno** [comment]
Should I update to 1.2 and make the screenshot with that capa version, or make them with v1.1.0?

**Comment by 0ssigeno** [comment]
This is what happens with v1.2.0:
image
This is what happens with v1.1.0:
image
Do you want me to debug a little more on why capa 1.2 behave like this, or should we stay with 1.1?

**Comment by Eshaan7** [comment]
>  Do you want me to debug a little more on why capa 1.2 behave like this, or should we stay with 1.1?

No. v1.1 is okay (for now atleast) because the error it's showing is raised inside the Flask-shell2http package. It's not an issue with the IntelOwl code. Flask-shell2http is my project so I'll debug it for v1.2 later.

Once again, thanks for the contribution!

**Pull request merged**
